"""empty message

Revision ID: 721e71347f5b
Revises: 51d923dbcb02
Create Date: 2024-08-11 22:44:01.122403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721e71347f5b'
down_revision: Union[str, None] = '51d923dbcb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcohol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alcohol_id'), 'alcohol', ['id'], unique=False)
    op.create_index(op.f('ix_alcohol_name'), 'alcohol', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alcohol_name'), table_name='alcohol')
    op.drop_index(op.f('ix_alcohol_id'), table_name='alcohol')
    op.drop_table('alcohol')
    # ### end Alembic commands ###
