"""empty message

Revision ID: a5a041988b97
Revises: 6b2c922dab95
Create Date: 2024-07-26 23:55:13.329732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a041988b97'
down_revision: Union[str, None] = '6b2c922dab95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamp_id'), 'stamp', ['id'], unique=False)
    op.create_index(op.f('ix_stamp_title'), 'stamp', ['title'], unique=False)
    op.create_table('stamp_rally',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamp_rally_description'), 'stamp_rally', ['description'], unique=False)
    op.create_index(op.f('ix_stamp_rally_id'), 'stamp_rally', ['id'], unique=False)
    op.create_index(op.f('ix_stamp_rally_title'), 'stamp_rally', ['title'], unique=False)
    op.create_table('stamp_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.Column('is_stamped', sa.Boolean(), nullable=True),
    sa.Column('stamp_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'stamp_id')
    )
    op.create_index(op.f('ix_stamp_result_id'), 'stamp_result', ['id'], unique=False)
    op.create_index(op.f('ix_stamp_result_is_stamped'), 'stamp_result', ['is_stamped'], unique=False)
    op.create_index(op.f('ix_stamp_result_stamp_id'), 'stamp_result', ['stamp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stamp_result_stamp_id'), table_name='stamp_result')
    op.drop_index(op.f('ix_stamp_result_is_stamped'), table_name='stamp_result')
    op.drop_index(op.f('ix_stamp_result_id'), table_name='stamp_result')
    op.drop_table('stamp_result')
    op.drop_index(op.f('ix_stamp_rally_title'), table_name='stamp_rally')
    op.drop_index(op.f('ix_stamp_rally_id'), table_name='stamp_rally')
    op.drop_index(op.f('ix_stamp_rally_description'), table_name='stamp_rally')
    op.drop_table('stamp_rally')
    op.drop_index(op.f('ix_stamp_title'), table_name='stamp')
    op.drop_index(op.f('ix_stamp_id'), table_name='stamp')
    op.drop_table('stamp')
    # ### end Alembic commands ###
