"""empty message

Revision ID: e1465c0b89b8
Revises: 
Create Date: 2024-08-16 22:33:03.611586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1465c0b89b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcohol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alcohol_id'), 'alcohol', ['id'], unique=False)
    op.create_index(op.f('ix_alcohol_name'), 'alcohol', ['name'], unique=False)
    op.create_table('stamp_rally',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamp_rally_description'), 'stamp_rally', ['description'], unique=False)
    op.create_index(op.f('ix_stamp_rally_id'), 'stamp_rally', ['id'], unique=False)
    op.create_index(op.f('ix_stamp_rally_title'), 'stamp_rally', ['title'], unique=False)
    op.create_table('stamp_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.Column('is_stamped', sa.Boolean(), nullable=True),
    sa.Column('stamp_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'stamp_id')
    )
    op.create_index(op.f('ix_stamp_result_id'), 'stamp_result', ['id'], unique=False)
    op.create_index(op.f('ix_stamp_result_is_stamped'), 'stamp_result', ['is_stamped'], unique=False)
    op.create_index(op.f('ix_stamp_result_stamp_id'), 'stamp_result', ['stamp_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_completed'), 'todos', ['completed'], unique=False)
    op.create_index(op.f('ix_todos_description'), 'todos', ['description'], unique=False)
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('stamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('alcohol_id', sa.Integer(), nullable=True),
    sa.Column('stamp_rally_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alcohol_id'], ['alcohol.id'], ),
    sa.ForeignKeyConstraint(['stamp_rally_id'], ['stamp_rally.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stamp_id'), 'stamp', ['id'], unique=False)
    op.create_index(op.f('ix_stamp_title'), 'stamp', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stamp_title'), table_name='stamp')
    op.drop_index(op.f('ix_stamp_id'), table_name='stamp')
    op.drop_table('stamp')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_description'), table_name='todos')
    op.drop_index(op.f('ix_todos_completed'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_stamp_result_stamp_id'), table_name='stamp_result')
    op.drop_index(op.f('ix_stamp_result_is_stamped'), table_name='stamp_result')
    op.drop_index(op.f('ix_stamp_result_id'), table_name='stamp_result')
    op.drop_table('stamp_result')
    op.drop_index(op.f('ix_stamp_rally_title'), table_name='stamp_rally')
    op.drop_index(op.f('ix_stamp_rally_id'), table_name='stamp_rally')
    op.drop_index(op.f('ix_stamp_rally_description'), table_name='stamp_rally')
    op.drop_table('stamp_rally')
    op.drop_index(op.f('ix_alcohol_name'), table_name='alcohol')
    op.drop_index(op.f('ix_alcohol_id'), table_name='alcohol')
    op.drop_table('alcohol')
    # ### end Alembic commands ###
